### ISSUE TITLE
ReflectionUtils method createInstanceOfType can improve performance？

### ISSUE THREAD

**Issue by sdcuike** [arteam/unitils#2]
ReflectionUtils method：
  public static <T> T createInstanceOfType(Class<T> type, boolean bypassAccessibility, Class[] argumentTypes,Object[] arguments)

if  type is interface ，we can throw expection，let security check not allowed？

**Comment by arteam** [comment]
Thanks for reporting this issue, but this fork is not actively maintained, it was created only for internal purposes. Please try to reach out to the original Unitils maintainers.
